
	SUBROUTINE BACKWARD_UPDATE_FX(FX1,LT)
	USE GRAPH
	IMPLICIT NONE 
	! TAIL(A)--------->HEAD(B)
	REAL*8,INTENT(OUT)::FX1(NL,NDEST)
	REAL*8,INTENT(IN)::LT(NL)
	INTEGER::I,J,NODE,NR,LINK
!UPDATE THE LABLE ON THE SUBNETWORK	
	FX1=LARGE
	
	NDIST = LARGE				
	DO NR = 1,NDEST
		NDIST(ROOTS(NR),NR) = 0.0
		DO I = NN,1,-1
			NODE = TORDER(I,NR)
			IF ((NODE.NE.0).AND.SUBNODE(NODE,NR)) THEN 
				DO J=FIRSTIN(NODE),LASTIN(NODE)
					LINK = BACKTOFORWARD(J)
                    IF (SUBLINK(LINK,NR)) THEN 
                        IF (NDIST(BNODE(LINK),NR)+LT(LINK).LT.NDIST(ANODE(LINK),NR)) THEN
                            NDIST(ANODE(LINK),NR) = NDIST(BNODE(LINK),NR)+LT(LINK)
                        END IF 
                        FX1(LINK,NR) = NDIST(BNODE(LINK),NR)+LT(LINK)
					END IF 
				END DO 
			END IF 
		END DO 
	ENDDO 

	RETURN
	END SUBROUTINE 

