		SUBROUTINE COUNTCONECT
		USE GRAPH
		IMPLICIT NONE 
		INTEGER I,NR,L,J,NODE
		INTEGER A, B
		NUMCONNECT = 0.0
		CONNECT = .FALSE.
		DO NR = 1,NDEST
			DO I = NN,1,-1
				NODE = TORDER(I,NR)
				IF (NODE.NE.0) THEN 
					DO J = FIRSTIN(NODE),LASTIN(NODE)
						L = BACKTOFORWARD(J)
						A = ANODE(L)
						B = BNODE(L)
						IF (SUBLINK(L,NR).AND.(SUBNODE(A,NR))) THEN
							CONNECT(A,B,NR) = .TRUE.
							NUMCONNECT(A,B,NR) = NUMCONNECT(A,B,NR) + 1
						END IF 
					ENDDO 
				ENDIF 
			ENDDO 
		ENDDO 

		RETURN 
		END 



