! This subroutine is used to update the flow for each node
! input is the flow propotion
! out put is the flow on each link
		SUBROUTINE FORWARD_UPDATE_FLOW(X0,XFA,LF,FIRSTOUT,LASTOUT)
		USE GRAPH
		IMPLICIT NONE 
		
		REAL*8,INTENT(IN)::X0(NL,NDEST)
		REAL*8,INTENT(OUT)::XFA(NL,NDEST)
		INTEGER,INTENT(IN)::FIRSTOUT(NN),LASTOUT(NN)
		REAL*8,INTENT(OUT)::LF(NL) ! LINK FLOW
		INTEGER I,J,NR!NR stands for number of root
		INTEGER NODE,LINK,O,D
		LF=0.0
		XFA = 0.0
		NF = 0.0 
	!	GO TO 10
	
!		DO I=1,NOD
!			IF (DEST(I)==ROOTS(NR)) THEN 
!				NF(ORIGIN(I),NR)=DEMAND(I)+NF(ORIGIN(I),NR)
!			ENDIF 
!		END DO 
		
		DO I=1,NOD
			O = ORIGIN(I)
			D = DEST(I)
			DO J=1,NDEST
				IF (ROOTS(J)==D) THEN 
					NR =J
					EXIT
				END IF 
			ENDDO  
			NF(O,NR)=NF(O,NR)+DEMAND(I)
		END DO 

		DO NR = 1,NDEST
			DO I = 1,NN
				NODE=TORDER(I,NR)
				IF (NODE.NE.0) THEN 
					DO J = FIRSTOUT(NODE),LASTOUT(NODE)
						LINK = J
						IF(SUBLINK(LINK,NR).AND.SUBNODE(BNODE(LINK),NR)) THEN 
							XFA(LINK,NR)=NF(ANODE(LINK),NR)*X0(LINK,NR)
							NF(BNODE(LINK),NR)=NF(BNODE(LINK),NR)+XFA(LINK,NR)
						END IF 
					ENDDO 
				END IF 
			ENDDO 
		ENDDO

		FORALL (I=1:NL)
			LF(I)=SUM(XFA(I,:))
		END FORALL 
	RETURN 
	END SUBROUTINE 
	
