! This subroutine is used to update the flow for each node
! input is the flow propotion
! out put is the flow on each link 
		SUBROUTINE CAL_FX(X0,FX1,XFA,FIRSTOUT,LASTOUT)
		USE GRAPH
		IMPLICIT NONE
		INTEGER,INTENT(IN)::FIRSTOUT(NN),LASTOUT(NN)
		REAL*8,INTENT(IN)::X0(NL,NDEST)
		REAL*8,INTENT(OUT)::FX1(NL,NDEST)
		REAL*8 XFA(NL,NDEST)
		REAL*8::LF(NL)  ! THIS IS LINK FLOW AND LINK TIME 
		CALL FORWARD_UPDATE_FLOW(X0,XFA,LF,FIRSTOUT,LASTOUT)
		CALL LINK_TIME(LF,STT)
		CALL BACKWARD_UPDATE_FX(FX1,STT)
		
		!DO NR = 1,NDEST
			!DO I = 1,NL
				!IF ((XFA(I,NR).GT.0).AND.(FX1(I,NR).EQ.LARGE)) THEN 
					!WRITE(*,*) "ISSUE"
				!END IF 
			!END DO 
		!END DO 
		RETURN 
		END SUBROUTINE

