		SUBROUTINE INITIAL_X(XFA,FIRSTOUT,LASTOUT)
		USE  GRAPH
		IMPLICIT NONE
		INTEGER::I
		INTEGER::L,NODE
		REAL*8,INTENT(IN)::XFA(NL,NDEST)
		INTEGER,INTENT(IN)::FIRSTOUT(NN),LASTOUT(NN)

		CALL NODE_FLOW(XFA)  	! INTIAL NODE FLOW
		X=0.0
		DO I = 1, NDEST
			DO L = 1, NL
				NODE = ANODE(L)
				IF (NF(NODE,I).NE.0.0) THEN 
					X(L,I) = XFA(L,I)/NF(NODE,I)
				END IF 
			END DO 
		END DO 
		DO I = 1, NDEST
			DO NODE =1, NN
				IF (SUBNODE(NODE,I)) THEN
					IF (NF(NODE,I).EQ.0.0) THEN 
						DO L = FIRSTOUT(NODE),LASTOUT(NODE)	
							IF(SUBLINK(L,I)) THEN
								X(L,I) = 1.0
								EXIT
							ENDIF 
						END DO 
					END IF 
				END IF 
			END DO 
		END DO 

		RETURN 
		END SUBROUTINE

