!	MINIUM SPANNING TREE
	SUBROUTINE MINSP(XFA)
	USE GRAPH
	IMPLICIT NONE 
	
	INTEGER I,O,ROOT,NR,NODE,ARC
	REAL*8::XFA(NL,NDEST)
	SUBNODE = .FALSE.
	SUBLINK = .FALSE.
	XFA=0.0
! MINIMUM SPANNING TREE
	DO NR =1,NDEST
		ROOT = ROOTS(NR)
		CALL RSP(ROOT,SCOST,FIRSTIN,LASTIN)
		NDIST(:,NR)=DIST(:)  ! SHORTEST DISTANCE
		DO I = 1, NN
			IF (PA(I).NE.0) THEN 
				ARC = PA(I)
				ARC = BACKTOFORWARD(ARC)
				SUBLINK(ARC,NR)=.TRUE.
				SUBNODE(ANODE(ARC),NR)=.TRUE.
				SUBNODE(BNODE(ARC),NR)=.TRUE.
			END IF 
		END DO
		DO I=1,NOD
			O=ORIGIN(I)
			NODE=O
			DO WHILE (NODE.NE.ROOT)
				ARC = PA(NODE)	
				SUBLINK(ARC,NR)=.TRUE.
				NODE = BACKANODE(ARC)	
				ARC = BACKTOFORWARD(ARC)
				XFA(ARC,NR) = XFA(ARC,NR) + DEMAND(I)
			END DO 
		ENDDO 
	END DO 
	RETURN 
	END SUBROUTINE


