		SUBROUTINE CAL_MSA_FX(FX0,LT)
		USE GRAPH
		IMPLICIT NONE
		! THIS SUBROUTEIN IS TO CALCULATE FX VALUE
		! INPUT IS X, WHICH IS PROPORTION
		! OUT PUT IS FX
		REAL*8,INTENT(OUT)::FX0(NL,NDEST)
		REAL*8,INTENT(IN)::LT(NL)
!		REAL*8::LT(NL)   ! THIS IS LINK FLOW AND LINK TIME 
	
		! STEP 1 UPDATE FLOW 
	
		! STEP 2 GET COST
!		CALL LINKTIME(LF,LT)
		! STEP 3 GET FX
		CALL SHORTEST_PATH_UPDATE_FX(LT,FX0)
		

		RETURN 
		END SUBROUTINE
		
		SUBROUTINE SHORTEST_PATH_UPDATE_FX(LT,FX0)
		USE GRAPH
		IMPLICIT NONE 
		
		INTEGER I,O,ROOT,NR,ARC,NODE
	!	REAL*8::LINKFLOW(NL,NDEST)
	!	REAL*8 NODE_DEMAND(NN,NDEST)
		REAL*8,INTENT(IN)::LT(NL)
		REAL*8,INTENT(OUT)::FX0(NL,NDEST)
		
		FX0 = 0.0
		DO NR =1,NDEST
			ROOT = ROOTS(NR)
		!	CALL RSP(ROOT,LT,FIRSTIN,LASTIN)
		!	CALL SUBRSP(ROOT,NR,LT,FIRSTIN,LASTIN)
			CALL RSP(ROOT,LT,FIRSTIN,LASTIN)
			NDIST(:,NR)=DIST(:)  ! SHORTEST DISTANCE
			DO I=1,NOD
				O=ORIGIN(I)
				NODE=O
				DO WHILE (NODE.NE.ROOT)
					ARC = PA(NODE)	
					NODE = BACKANODE(ARC)	
					ARC = BACKTOFORWARD(ARC)
					FX0(ARC,NR) = FX0(ARC,NR) + DEMAND(I)
			END DO 
		ENDDO 
		END DO 


		RETURN 

		END SUBROUTINE 
