!this function is to calculate the norm value
REAL*8 FUNCTION NORM_VALUE(VECTOR,N)
IMPLICIT NONE
INTEGER,INTENT(IN)::N
REAL*8,DIMENSION(N)::VECTOR
REAL*8:: RESULTS
INTEGER::I
RESULTS=0.0
DO I=1,N
RESULTS=RESULTS+VECTOR(I)*VECTOR(I)
END DO 
NORM_VALUE=SQRT(RESULTS)

RETURN

END FUNCTION

REAL*8 FUNCTION NORM_VALUE2(V1,V2,N1,N2)
IMPLICIT NONE
INTEGER,INTENT(IN)::N1,N2
REAL*8,DIMENSION(N1,N2)::V1,V2
REAL*8:: RESULTS
INTEGER::I,J
RESULTS=0.0
DO I=1,N1
	DO J=1,N2
	RESULTS=RESULTS+(V1(I,J)-V2(I,J))**2
	END DO 
END DO 
NORM_VALUE2=SQRT(RESULTS)

RETURN

END FUNCTION

REAL*8 FUNCTION NORM_VALUE0(VECTOR,N1,N2)
IMPLICIT NONE
INTEGER,INTENT(IN)::N1,N2
REAL*8,DIMENSION(N1,N2)::VECTOR
REAL*8:: RESULTS
INTEGER::I,J
RESULTS=0.0
DO I=1,N1
	DO J=1,N2
	RESULTS=RESULTS+VECTOR(I,J)**2
	END DO 
END DO 
NORM_VALUE0=SQRT(RESULTS)

RETURN

END FUNCTION



