		SUBROUTINE SUBRSP(R,NR,LINK_TIME,FIRSTOUT,LASTOUT)
		USE  GRAPH
		IMPLICIT NONE 
         
		INTEGER I, N1, N2,NR
	!   DO LOOP INDEX
		INTEGER,INTENT(IN)::R
		INTEGER P, ND
		INTEGER,INTENT(IN)::FIRSTOUT(NN),LASTOUT(NN)
	!   ROOT, INTERMEDIATE NODE
		INTEGER ARC
	!   LINK NUMBER
		INTEGER Q(NN)
	!   QUEUE OF NODES TO BE SCANNED
		INTEGER ENDQ
	!   MARK THE LAST ELEMENT OF THE QUEUE ARRAY
		REAL*8 D1, DP
	!   NODE DISTANCE
		INTEGER ILARGE
	!   A NUMBER LARGER THAN NN
		REAL*8 XLARGE

	!   A LARGE NUMBER
	!	REAL*8 DIST(NN)    
	!	NODE LABLES
	!	INTEGER PA(NN)
	!	PREDECESSOR ARC	
	!	INTEGER IMAX
!		INTEGER DESTINATION
	!	INTEGER NP
		REAL*8,INTENT(IN)::LINK_TIME(NL)
	!	CALL READ_DATA
	!	R=1		! ORIGINAL NODE
	!	IMAX=30		! MAXIMUM NUMBER OF ITERATION FOR DOUBLE SWEEPING
	!	CALL  DSWP(R,IMAX) 
	!	CALL TRACE(R,DESTINATION,KSP,NP)
	!	XLARGE=1E+9
		XLARGE = LARGE
		ILARGE = NN+1
		PA = 0
      	
   !   	FIRSTOUT = FFOUT(:,R)
  !    	LASTOUT=FLOUT(:,R)
	!     INITIALIZE LABELS

		  DO I = 1, NN
			 DIST(I) = XLARGE
			 Q(I) = 0
		  ENDDO

	!     SET LABELS FOR ROOT NODE    
		  DIST(R) = 0.0
		  Q(R) = ILARGE 
		  ENDQ = R
		  P = R
      
	!     START OF MAIN ALGORITHM

	100   CONTINUE

		  N1 = FIRSTOUT(P)
		  IF (N1.EQ.0) GOTO 201
		  N2 = LASTOUT(P)
		  DP = DIST(P)
		  DO 10 ARC = N1, N2
	!		 ND = BNODE(ARC)
			 ND = BACKBNODE(ARC)
	!		 D1 = DP + LINK_TIME(ARC)
			 D1 = DP + LINK_TIME(BACKTOFORWARD(ARC))
			 IF (D1.GE.DIST(ND).OR.(.NOT.SUBLINK(BACKTOFORWARD(ARC),NR)).OR.(.NOT.SUBNODE(ND,NR))) GO TO 10
	!
	!     CHANGE DISTANCE AND LABEL OF NODE ND
	!
			 PA(ND) = ARC
			 DIST(ND) = D1
			 IF (Q(ND)) 30, 20, 10
			! if i>0,  10
			! if i=0,  20,30,10 
			! if i=-1 30,10 
	!     IF ND HAS NEVER BEEN SCANNED INSERT IT AT THE END OF THE QUEUE
	!
	20       Q(ENDQ) = ND
			 ENDQ = ND
			 Q(ND) = ILARGE
			 GO TO 10
	!
	!     IF ND HAS ALREADY BEEN SCANNED ADD IT AT THE BEGINNING OF THE
	!     QUEUE AFTER NODE P
	!
	30       Q(ND) = Q(P)
			 Q(P) = ND
          
			 IF (ENDQ.EQ.P) ENDQ = ND
         
	10    CONTINUE
	!
	!     GET NEXT NODE FROM THE TOP OF THE QUEUE
	!
	201   N1 = Q(P)

	!     FLAG P AS HAVING BEEN SCANNED

		  Q(P) = -1
		  P = N1


	!     IF THE QUEUE IS NOT EMPTY GO BACK TO SCAN NEXT NODE

		 IF (P.LT.ILARGE) GO TO 100
      
!		WRITE(*,*) "FINSIH"
		
		END SUBROUTINE 
