	SUBROUTINE GETORDER(LT)	
	USE GRAPH	
	IMPLICIT NONE
	REAL*8 LT(NL)
	INTEGER NR,I
	INTEGER NODE, LINK,J
!	NLT=-LT
	DO NR = 1,NDEST
!		ROOT = ROOTS(NR)
		CALL ORDER(NR,NDIST(:,NR))
		!DO I=1,NN
			!IF (TORDER(I,NR)/=0) THEN 
			!IF (.NOT.SUBNODE(TORDER(I,NR),NR)) THEN 
			!WRITE(*,*) "WRONG NODE INCLUDED"
			!END IF 
			!END IF 
		!END DO 
	END DO 
! FIND THE LAREGEST COST LABLE
	LNDIST = 0.0
	DO NR = 1,NDEST
		DO I = NN,1,-1
			NODE = TORDER(I,NR) 
			IF (NODE.NE.0) THEN 
				DO J = FIRSTIN(NODE),LASTIN(NODE)
					LINK = BACKTOFORWARD(J)
					IF (SUBNODE(ANODE(LINK),NR)) THEN 
						IF (LNDIST(ANODE(LINK),NR).LT.LNDIST(BNODE(LINK),NR)+LT(LINK)) THEN 
								LNDIST(ANODE(LINK),NR) = LNDIST(BNODE(LINK),NR)+LT(LINK)
						END IF 
					ENDIF 
				ENDDO 
			END IF 
		ENDDO 
	ENDDO 
	
	END SUBROUTINE


	SUBROUTINE ORDER(NR,LABLE)
	USE GRAPH
	IMPLICIT NONE 
	INTEGER,INTENT(IN):: NR
	REAL*8,INTENT(IN)::LABLE(NN)
	INTEGER I,J,TI
	REAL*8 VEC(NN),TEMP
	FORALL(I=1:NN)
		TORDER(I,NR)=I
	ENDFORALL

	VEC(:)=LABLE(:)
	DO I=1, NN
		DO J=NN, I+1, -1
			 IF (VEC(J-1).LE.VEC(J)) THEN 
				TEMP = VEC(J-1)
				VEC(J-1) = VEC(J)
				VEC(J) = TEMP
				TI =  TORDER(J-1,NR)
				TORDER(J-1,NR) =  TORDER(J,NR)
				TORDER(J,NR) = TI
				END IF 
			END DO 
		END DO 
		DO I = 1,NN
			IF (VEC(I).GE.LARGE) THEN
				TORDER(I,NR) = 0
			END IF
		END DO  
		RETURN

		END SUBROUTINE
