	SUBROUTINE UPDATESUB(LT,DEL,XFA)
	USE GRAPH
	IMPLICIT NONE 

	!STEP 
	REAL*8,INTENT(IN)::LT(NL)
	LOGICAL,INTENT(IN)::DEL
	REAL*8,INTENT(IN)::XFA(NL,NDEST)
	INTEGER NR,NODE,I,J,LINK,A,B,L
! FIRST ADD NEW LINKS 	
	IF (.NOT.DEL) THEN 
		GOTO 5
	ELSE 
		DO NR = 1,NDEST
			DO  L = 1, NL 
				IF (SUBLINK(L,NR)) THEN 
					IF (XFA(L,NR).LE.FLOW_EPS) THEN 
						A = ANODE(L)
						B = BNODE(L)
						IF (CONNECT(A,B,NR).AND.(NUMCONNECT(A,B,NR)-1.GE.1)) THEN
							SUBLINK(L,NR) = .FALSE.
							NUMCONNECT(A,B,NR) = NUMCONNECT(A,B,NR) - 1
							WRITE(*,*) "DEL LINK"
						END IF 
					END IF 
				END IF 
			ENDDO 
		ENDDO  
	END IF 


! ADD LINK

5	UECONVERGE = .TRUE.
! STEP 1 UPDATE LABLE
	NDIST = LARGE				
	DO NR = 1,NDEST
		NDIST(ROOTS(NR),NR) = 0.0
		DO I = NN,1,-1
			NODE = TORDER(I,NR)
			IF ((NODE.NE.0).AND.SUBNODE(NODE,NR)) THEN 
				DO J=FIRSTIN(NODE),LASTIN(NODE)
					LINK = BACKTOFORWARD(J)
					IF (SUBLINK(LINK,NR)) THEN 
						IF (NDIST(BNODE(LINK),NR)+LT(LINK).LT.NDIST(ANODE(LINK),NR)) THEN
							NDIST(ANODE(LINK),NR) = NDIST(BNODE(LINK),NR)+LT(LINK)
					!		WRITE(*,*) "UP NDIST"
						END IF 
					END IF 
				END DO 
			END IF 
		END DO 
	ENDDO

	DO NR = 1,NDEST
		DO I = NN,1,-1
			NODE = TORDER(I,NR)
			IF (NODE.NE.0) THEN 
				DO J = FIRSTIN(NODE),LASTIN(NODE)
					LINK = BACKTOFORWARD(J)
					IF ((.NOT.SUBLINK(LINK,NR))) THEN 
						IF (LT(LINK)+NDIST(BNODE(LINK),NR).LT.NDIST(ANODE(LINK),NR)) THEN 
							IF (LNDIST(BNODE(LINK),NR).LT.LNDIST(ANODE(LINK),NR)) THEN
								SUBLINK(LINK,NR) = .TRUE.
								NUMCONNECT(ANODE(LINK),BNODE(LINK),NR) = NUMCONNECT(ANODE(LINK),BNODE(LINK),NR) + 1
								UECONVERGE = .FALSE.
					!			WRITE(*,*) "ADDLNK"
							END IF
						END IF 
					END IF 
				END DO 
			END IF 
		END DO 
	END DO
	 
    RETURN
	END SUBROUTINE 

					
