    SUBROUTINE OUTPUTX(FLOW,Y)
    USE  GRAPH
    IMPLICIT NONE
    INTEGER I,J
    REAL*8::FLOW(NL,NDEST),Y(NL,NDEST)
    OPEN(29,FILE='..\..\RESULTS\FORTRAN_OUTPUTXY.TXT')
    DO I=1,NDEST
        DO J=1,NL
            IF (FLOW(J,I)/=0.0) THEN
                WRITE(29,"(I3,A,I2,A,I3,A,F6.2,A,F7.2)") CASEINDEX,',', I,',',J,',',FLOW(J,I),',',Y(J,I)
            ENDIF
        ENDDO
    END DO
    END SUBROUTINE

    SUBROUTINE OUTPUTOD(FLOW,Y)
    USE  GRAPH
    IMPLICIT NONE
    INTEGER I,J
    REAL*8::FLOW(NL,NDEST),Y(NL,NDEST)
    INTEGER Q,W

    !OPEN(39,FILE='C:\GITCODES\APPROACHCODE\RESULTS\OUTPUTOD.TXT',STATUS='REPLACE' )
    ! THIS IS PRINT OUT ALL THE OD PAIRS
    OPEN(39,FILE='..\..\RESULTS\FORTRAN_OUTPUTOD.TXT',STATUS='OLD', POSITION='APPEND' )
    !INTEGER::DEST(NOD),ORIGIN(NOD)
    DO Q = 1, NOD
        DO W=1,NDEST
            IF (ROOTS(W).EQ.DEST(Q)) THEN
                DO J = 1, NL
                    IF (ANODE(J).EQ.ORIGIN(Q)) THEN
                        !WRITE(39,"(I2,1X,I3,1X,1X,F7.2)") ORIGIN(Q),DEST(Q),Y(J,W)
                        IF (FLOW(J,W)>0.0001) THEN
                            !WRITE(39,"(I2,1X,I3,1X,F6.2,1X,F7.2)") ORIGIN(Q),DEST(Q),DEMAND(Q),Y(J,W)
                            !WRITE(39,"(I2,A,I3,A,F6.2,A,F7.2)") ORIGIN(Q),',',DEST(Q),',', DEMAND(Q),',',Y(J,W)
                            WRITE(39,"(I3,A,I2,A,I3,A,F8.4,A,F8.4,A,F8.4)") &
                                CASEINDEX,',',ORIGIN(Q),',',DEST(Q),',', DEMAND(Q),',',Y(J,W),',',FLOW(J,W)
                            EXIT
                        ENDIF
                    ENDIF
                ENDDO
            ENDIF
        ENDDO
    ENDDO

    END SUBROUTINE



    SUBROUTINE OUTPUTPATH(LINKTIME, XFA)
    USE  GRAPH
    IMPLICIT NONE
    INTEGER I,J
    REAL*8::LINKTIME(NL)
    REAL*8,INTENT(IN)::XFA(NL,NDEST)

    !OPEN(1,FILE='C:\GITCODES\APPROACHCODE\RESULTS\LINKCOST.TXT',STATUS='REPLACE' )
    OPEN(3,FILE='..\..\RESULTS\FORTRAN_LINKCOST.TXT',STATUS='OLD', POSITION='APPEND' )
    !INTEGER::DEST(NOD),ORIGIN(NOD)

    DO I = 1, NL
        WRITE(3,'(I2,A,F8.4)') CASEINDEX,',',LINKTIME(I)
    ENDDO

    CLOSE(3)

    !#OPEN(1,FILE='C:\GITCODES\APPROACHCODE\RESULTS\PATHCOST.TXT',STATUS='REPLACE')
    OPEN(1,FILE='..\..\RESULTS\FORTRAN_PATHCOST.TXT',STATUS='OLD', POSITION='APPEND' )

    ! THE SECOND DEMMENSION OF THE XFA IS THE DESTINATION INDEX
    ! THE FIRST THREE PATHS BLONG TO OD PAIR 1-4
    WRITE(1,'(I3,A,F8.4,A,F8.4)') CASEINDEX,',',XFA(3,1),',',LINKTIME(3)
    WRITE(1,'(I3,A,F8.4,A,F8.4)') CASEINDEX,',',XFA(2,1),',',LINKTIME(2)+LINKTIME(6)
    WRITE(1,'(I3,A,F8.4,A,F8.4)') CASEINDEX,',',XFA(1,1),',',LINKTIME(1)+LINKTIME(4)+LINKTIME(6)
    ! THE FOLLOWING TWO BELONGS TO OD PAIR 2-4
    WRITE(1,'(I3,A,F8.4,A,F8.4)') CASEINDEX,',',XFA(4,1),',',LINKTIME(4)+LINKTIME(6)
    WRITE(1,'(I3,A,F8.4,A,F8.4)') CASEINDEX,',',XFA(5,1),',',LINKTIME(5)
    ! THE LAST BELONG TO OD PAIR  3-4
    WRITE(1,'(I3,A,F8.4,A,F8.4)') CASEINDEX,',',XFA(6,1),',',LINKTIME(6)


    CLOSE(1)

    END SUBROUTINE



    SUBROUTINE OUTPUTPARA
    USE GRAPH
    IMPLICIT NONE
    INTEGER I

    OPEN(1,FILE='..\..\RESULTS\FORTRAN_6LINKDATA.TXT')
    DO I = 1, 6
        WRITE (1,'(F6.2,A,F6.2,A,F6.2)') SCOST(I),',', SVAR(I),',',FARE(I)
    ENDDO
    CLOSE(1)


    !
    !OPEN(1,FILE='..\..\RESULTS\FORTRAN_LINECOSTANDVAR.TXT')
    !WRITE(1,'(F6.2,A,F6.2)') TSL(1,1),',',TSL(1,2)  ! LINE 1
    !WRITE(1,'(F6.2,A,F6.2)') TSL(7,1),',',TSL(7,2)  ! LINE 2
    !WRITE(1,'(F6.2,A,F6.2)') TSL(8,1),',',TSL(8,2)  ! LINE 3
    !WRITE(1,'(F6.2,A,F6.2)') TSL(6,1),',',TSL(6,2)  ! LINE 4
    !CLOSE(1)

    END SUBROUTINE





    !DO I=1,NDEST
    !DO J=1,NL
    !IF (FLOW(J,I)/=0.0) THEN
    !WRITE(29,"(I2,1X,I3,1X,F6.2,1X,F7.2)") I,J,FLOW(J,I),Y(J,I)
    !ENDIF
    !ENDDO
    !END DO
    !END SUBROUTINE

