!
!INTEGER,PARAMETER::MaxSecLine=4
!INTEGER,PARAMETER::SUBMAX = 0
!INTEGER,PARAMETER::NDEST=1  !NUMBER OF DISTINATIONS
!INTEGER,PARAMETER::NLINE=4	! NUMBER OF LINE
!INTEGER,PARAMETER::NOD=2	! NUMBER OF OD PAIRS
!INTEGER,PARAMETER::NN=4   ! NUMBER OF NODES
!INTEGER,PARAMETER::MaxCom = 10
!INTEGER,PARAMETER::MaxLineStops=4
